# Generated by Django 2.0.5 on 2018-06-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_diarypost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='diarypost',
            options={'ordering': ('-timestamp',)},
        ),
    ]
